# Generated by Django 3.0.5 on 2021-06-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название БД')),
            ],
            options={
                'verbose_name': 'База данных',
                'verbose_name_plural': 'Базы данных',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название подписки')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='database_separator.DataBase', verbose_name='БД')),
            ],
        ),
        migrations.CreateModel(
            name='ReplicationSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название слота')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_slots', to='database_separator.DataBase', verbose_name='БД')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название публикации')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='database_separator.DataBase', verbose_name='БД')),
            ],
        ),
    ]
