# Generated by Django 3.0.5 on 2021-06-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0002_auto_20210615_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Таблица в публикации')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_separator.Publication', verbose_name='Публикация')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='tables',
            field=models.ManyToManyField(blank=True, to='database_separator.PubTables', verbose_name='Таблицы'),
        ),
    ]
