# Generated by Django 3.0.5 on 2021-06-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0003_auto_20210615_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='tables',
        ),
    ]
