# Generated by Django 3.0.5 on 2021-06-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0005_auto_20210615_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(verbose_name='Начальное значение')),
                ('end', models.IntegerField(verbose_name='Конечное значение')),
                ('database', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database_separator.DataBase', verbose_name='БД')),
            ],
            options={
                'verbose_name': 'Диапазон для БД',
                'verbose_name_plural': 'Диапазоны для БД',
            },
        ),
    ]
