# Generated by Django 3.0.5 on 2021-06-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0006_sequencerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencerange',
            name='database',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='database_separator.DataBase', verbose_name='БД'),
        ),
    ]
