# Generated by Django 3.0.5 on 2021-06-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0007_auto_20210621_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencerange',
            old_name='end',
            new_name='max',
        ),
    ]
