# Generated by Django 3.0.5 on 2021-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0008_auto_20210621_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencerange',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
