# Generated by Django 3.0.5 on 2021-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0009_sequencerange_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencerange',
            name='database',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='БД'),
        ),
    ]
