# Generated by Django 3.0.5 on 2021-08-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0010_auto_20210705_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='to_database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_to_me', to='database_separator.DataBase', verbose_name='к БД'),
        ),
    ]
