# Generated by Django 3.0.5 on 2021-12-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0011_subscription_to_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.IntegerField(verbose_name='Контрольная сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_separator.DataBase', verbose_name='База данных')),
            ],
            options={
                'verbose_name': 'Контрольная сумма',
                'verbose_name_plural': 'Контрольные суммы',
            },
        ),
    ]
