# Generated by Django 3.0.5 on 2021-12-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_separator', '0012_checksum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checksum',
            name='db',
        ),
    ]
